using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Problem_2
{
    class Program
    {
        static void Main(string[] args)
        {
            /*
               Even Fibonacci numbers
               Problem 2
                Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
                By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
            */
            int v1 = 0, v2 = 1;
            int fib = 0;
            int sum = 0;
            while (fib < 4000000)
            {
                if (fib % 2 == 0)
                {
                    sum += fib;
                }

                fib = v1 + v2;
                v1 = v2;
                v2 = fib;
            }
        }
    }
}
